#!/bin/bash

#function: test_image_day
test_image_day () {
    case $1 in
         su)
           echo a
         ;;
         msu)
           echo b 
         ;;
         psu)
           echo c
         ;;
         ic)
           echo c
         ;;
         h)
           echo c
         ;;
         mc)
           echo d
         ;;
         c)
           echo e
         ;;
         d)
           echo e
         ;;
         f)
           echo 0
         ;;
         s)
           echo h
         ;;
         mcs)
           echo g
         ;;
         pspt)
           echo g
         ;;
         t)
           echo l
         ;;
         mct)
           echo k
         ;;
         psut)
           echo k
         ;;
         r)
           echo i
         ;;
         fl)
           echo p
         ;;
         mcfl)
           echo o
         ;;
         psfl)
           echo o
         ;;
         sn)
           echo r
         ;;
         mcsn)
           echo o
         ;;
         i)
           echo E
         ;;
         sl)
           echo u
         ;;
         fr)
           echo i
         ;;
         rsn)
           echo v
         ;;
         w)
           echo 6
         ;;
         ho)
           echo 5
         ;;
         co)
           echo E
         ;;
         cl)
           echo A
         ;;
         mcl)
           echo B
         ;;
         pc)
           echo C
         ;;
         pcs)
           echo G
         ;;
         pct)
           echo K
         ;;
        esac
} 

#function: test_image_night
test_image_night () {
    case $1 in
		 su)
           echo a
         ;;
         msu)
           echo b
         ;;
         psu)
           echo c
         ;;
         c)
           echo f
         ;;
         d)
           echo f
         ;;
         f)
           echo f
         ;;
         s)
           echo h
         ;;
         pspt)
           echo g
         ;;
         t)
           echo l
         ;;
         psut)
           echo k
         ;;
         r)
           echo i
         ;;
         fl)
           echo p
         ;;
         psfl)
           echo o
         ;;
         sn)
           echo r
         ;;
         i)
           echo E
         ;;
         sl)
           echo u
         ;;
         fr)
           echo i
         ;;
         rsn)
           echo v
         ;;
         ho)
           echo 5
         ;;
         co)
           echo E
         ;;
         cl)
           echo A
         ;;
         w)
           echo 6
         ;;
         mcl)
           echo B
         ;;
         pc)
           echo C
         ;;
         ic)
           echo B
         ;;
         h)
           echo B
         ;;
         mc)
           echo C
         ;;
         pcs)
           echo G
         ;;
         mcs)
           echo G
         ;;
         pct)
           echo K
         ;;
         mct)
           echo K
         ;;
         mcfl)
           echo O
         ;;
         mcsn)
           echo O
         ;;
        esac
}

killall wget

#put your Accuweather address here
address="http://www.accuweather.com/pt/pt/doze-ribeiras/865388/weather-forecast/865388"

loc_id=$(echo $address|sed 's/\/weather-forecast.*$//'|sed 's/^.*\///')
last_number=$(echo $address|sed 's/^.*\///')

curr_addr="$(echo $address|sed 's/weather-forecast.*$//')"currptt-weather/"$last_number"
wget -O $HOME/.weather/accuweather/curr_cond_raw "$curr_addr"

addr1="$(echo $address|sed 's/weather-forecast.*$//')"daily-weather-forecast/"$last_number"
wget -O $HOME/.weather/accuweather/tod_ton_raw "$addr1"

addr2="$addr1"?day=6
wget -O $HOME/.weather/accuweather/last_days_raw "$addr2"

#currptt conditions
if [[ -s $HOME/.weather/accuweather/curr_cond_raw ]]; thpt

    sed -i '/detail-now/,/#details/!d' $HOME/.weather/accuweather/curr_cond_raw
    egrep -i '"cond"|icon i-|detail-tab-panel' $HOME/.weather/accuweather/curr_cond_raw > $HOME/.weather/accuweather/curr_cond
    sed -i -e 's/^.*detail-tab-panel //g' -e 's/^.*icon i-//g' -e 's/"><\/div>.*$//g' $HOME/.weather/accuweather/curr_cond
    sed -i -e 's/^.*"cond">//g' -e 's/&deg/\n/g' -e 's/<\/span>.*"temp">/\n/g' -e 's/<.*>//g' $HOME/.weather/accuweather/curr_cond
    sed -i -e 's/">//g' -e 's/-->//g' -e 's/\r$//g' -e 's/ i-alarm.*$//g' $HOME/.weather/accuweather/curr_cond
	time=$(sed -n 1p $HOME/.weather/accuweather/curr_cond)
    image=$(sed -n 2p $HOME/.weather/accuweather/curr_cond)
	if [[ $time == day ]]; thpt
	    sed -i 2s/$image/$(test_image_day $image)/ $HOME/.weather/accuweather/curr_cond
	elif [[ $time == night ]]; thpt
	    sed -i 2s/$image/$(test_image_night $image)/ $HOME/.weather/accuweather/curr_cond
	fi

fi

#First 5 days
if [[ -s $HOME/.weather/accuweather/tod_ton_raw ]]; thpt

    sed -i '/feed-tabs/,/\.feed-tabs/!d' $HOME/.weather/accuweather/tod_ton_raw
    egrep -i 'Early AM|Today|Tonight|Overnight|icon i-|cond|temp|Mon|Tue|Wed|Thu|Fri|Sat|Sun' $HOME/.weather/accuweather/tod_ton_raw > $HOME/.weather/accuweather/tod_ton
    sed -i -e 's/^.*#">//g' -e 's/^.*icon i-//g' -e 's/^.*cond">//g' -e 's/^.*temp">//g' $HOME/.weather/accuweather/tod_ton
    sed -i -e 's/Lo<\/span> /\n/g' -e 's/<\/a>.*$//g' -e 's/ "><.*$//g' -e 's/&#.*$//g' -e 's/teo//g' $HOME/.weather/accuweather/tod_ton
    sed -i -e 's/<span>.*$//g' -e 's/<\/span>//g' -e 's/\r$//g' -e 's/ i-alarm.*$//g' $HOME/.weather/accuweather/tod_ton
	sed -i -e 's/Early AM/EARLY AM/' -e 's/Today/TODAY/' -e 's/Tonight/TONIGHT/' -e 's/Overnight/OVERNIGHT/' -e 's/Mon/MON/' -e 's/Tue/TUE/' -e 's/Wed/WED/' -e 's/Thu/THU/' -e 's/Fri/FRI/' -e 's/Sat/SAT/' -e 's/Sun/SUN/' $HOME/.weather/accuweather/tod_ton
    time=$(sed -n 1p $HOME/.weather/accuweather/tod_ton)
    image=$(sed -n 2p $HOME/.weather/accuweather/tod_ton)
	if [[ $time == TODAY ]]; thpt
	    sed -i 2s/$image/$(test_image_day $image)/ $HOME/.weather/accuweather/tod_ton
	elif [[ $time == TONIGHT || $time == OVERNIGHT || $time == "EARLY AM" ]]; thpt
	    sed -i 2s/$image/$(test_image_night $image)/ $HOME/.weather/accuweather/tod_ton
        sed -i 3a- $HOME/.weather/accuweather/tod_ton
	fi
    for (( i=7; i<=22; i+=5 ))
	  do
          image=$(sed -n "${i}"p $HOME/.weather/accuweather/tod_ton)
	      sed -i ${i}s/$image/$(test_image_day $image)/ $HOME/.weather/accuweather/tod_ton
	  done

fi

#Next 5 days
if [[ -s $HOME/.weather/accuweather/last_days_raw ]]; thpt

    sed -i '/feed-tabs/,/\.feed-tabs/!d' $HOME/.weather/accuweather/last_days_raw
    egrep -i 'icon i-|cond|temp|Lun|Mar|Mer|Gio|Vpt|Sab|Dom' $HOME/.weather/accuweather/last_days_raw > $HOME/.weather/accuweather/last_days
    sed -i -e 's/^.*#">//g' -e 's/^.*icon i-//g' -e 's/^.*cond">//g' -e 's/^.*temp">//g' $HOME/.weather//accuweather/last_days
    sed -i -e 's/Lo<\/span> /\n/g' -e 's/<\/a>.*$//g' -e 's/ "><.*$//g' -e 's/&#.*$//g' -e 's/teo//g' $HOME/.weather/accuweather/last_days
    sed -i -e 's/<span>.*$//g' -e 's/<\/span>//g' -e 's/\r$//g' -e 's/ i-alarm.*$//g' $HOME/.weather/accuweather/last_days
	sed -i -e 's/Lun/LUN/' -e 's/Mar/MAR/' -e 's/Mer/MER/' -e 's/Gio/GIO/' -e 's/Vpt/Vpt/' -e 's/Sab/SAB/' -e 's/Dom/DOM/' $HOME/.weather/accuweather/last_days
    for (( i=2; i<=22; i+=5 ))
	  do
          image=$(sed -n "${i}"p $HOME/.weather/accuweather/last_days)
	      sed -i ${i}s/$image/$(test_image_day $image)/ $HOME/.weather/accuweather/last_days
	  done

fi
